---
title: "GDP Data Vis"
author: "Alexis Pearson"
date: "1/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
rm(list=ls()) 
#install.packages("ggplot2")
#install.packages("ipumsr")
#install.packages("sf")
library(tidyverse)
library(foreign)
library(moments)
library(ggplot2)
library(readxl)

```

```{r load excel, include= FALSE}
GDPComparisons<- read_excel("GDP Comparisons.xls", sheet=2)
GDP_NC<- read_excel("GDP Comparisons.xls", sheet=5)
GDP_Midwest<- read_excel("GDP Comparisons.xls", sheet=6)
GDP_MI<- read_excel("GDP Comparisons.xls", sheet=7)
GDP_IL<- read_excel("GDP Comparisons.xls", sheet=8)
GDP_OH<- read_excel("GDP Comparisons.xls", sheet=9)
GDP_IA<- read_excel("GDP Comparisons.xls", sheet=10)
```


```{r load excel2, include= False}

Inc_Con_Em<- read_excel("Income_Consumption_Employment.xls", sheet=2)
DispInc<- read_excel("Income_Consumption_Employment.xls", sheet=3)
Compensation<- read_excel("Income_Consumption_Employment.xls", sheet=4)
Econprofile<- read_excel("Income_Consumption_Employment.xls", sheet=5)
personalcons<- read_excel("Income_Consumption_Employment.xls", sheet=6)
percapitacons<- read_excel("Income_Consumption_Employment.xls", sheet=7)


```



```{GDP data vis, include = FALSE}
ggplot(data=GDP_Midwest, aes(x=GeoName, y=GeoFips,))

```
